### ISSUE TITLE
All files are 0k on RP-WD03

### ISSUE THREAD

**Issue by grovo** [derfrankie/RAVPower-FileHub-SD-Backup#2]
Hello, i ve tried to hack my RavPower filehub V3 with your script. When i start it with SD card and USB hdd plugged in, it start to copy files but all files are 0k on my usb hdd.
I m not a programmer so i don t understand all your code but if i can test or try something...
thanks

**Comment by derfrankie** [comment]
Hi,
other RP-WD03 users did contact me and didn't have this problem.
I assume you setup everything as in the tutorial.
Did you let it run until no more blinking was involved?
What is the file system on the HDD?

thx
