### ISSUE TITLE
Allow user to specify what file type to backup

### ISSUE THREAD

**Issue by JackT2K** [derfrankie/RAVPower-FileHub-SD-Backup#3]
Not sure where to put this but im not sure where at in the script i would specify the specific file type I want. IE: I only want to copy over .jpg files

**Comment by derfrankie** [comment]
There is no general way implemented - but you could add a filter in the rsync command itself. Example

rsync -vrm --size-only --log-file $log_dir/rsync_log --exclude ".?*" \
                $SD_MOUNTPOINT/DCIM"/*.JPG"

Might add something in the next release.
